### ISSUE TITLE
Create Release from CI Builds from azure

### ISSUE THREAD

**Issue by illusion0001** [illusion0001/rpcs3#2]

**Comment by anatoliyz** [comment]
Hi! I'd like to build and test a native ARM build of your version for my MacBook M1 Pro. I'm following this build instructions:

https://github.com/RPCS3/rpcs3/files/10694905/RPCS3.Build.instructions.txt

I receive the following output:

```CMake Warning at 3rdparty/llvm/CMakeLists.txt:56 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible with requested version "16.0".

  The following configuration files were considered but not accepted:

    /usr/local/opt/llvm/lib/cmake/llvm/LLVMConfig.cmake, version: 18.1.4
    /usr/local/opt/llvm/lib/cmake/llvm/llvm-config.cmake, version: unknown

CMake Warning at 3rdparty/llvm/CMakeLists.txt:58 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible with requested version "17.0".

  The following configuration files were considered but not accepted:

    /usr/local/opt/llvm/lib/cmake/llvm/LLVMConfig.cmake, version: 18.1.4
    /usr/local/opt/llvm/lib/cmake/llvm/llvm-config.cmake, version: unknown

CMake Error at 3rdparty/llvm/CMakeLists.txt:67 (message):
  Can't find LLVM libraries from the CMAKE_PREFIX_PATH path or LLVM_DIR.
  													 Enable BUILD_LLVM option to build LLVM from included as a git submodule.```
  													 
 Can you please provide me with support on building your version locally? Thanks in advance!

**Comment by anatoliyz** [comment]
Trying this now

```
cmake .. \
	-DCMAKE_CXX_STANDARD=20\
	-DCMAKE_OSX_ARCHITECTURES="arm64"\
	-DLLVM_BUILD_RUNTIME=OFF\
	-DLLVM_BUILD_TOOLS=OFF\
	-DLLVM_CCACHE_BUILD=OFF\
	-DLLVM_ENABLE_Z3_SOLVER=OFF\
	-DLLVM_INCLUDE_DOCS=OFF\
	-DLLVM_INCLUDE_EXAMPLES=OFF\
	-DLLVM_INCLUDE_TESTS=OFF\
	-DLLVM_INCLUDE_TOOLS=OFF\
	-DLLVM_INCLUDE_UTILS=OFF\
	-DLLVM_TARGETS_TO_BUILD="X86;AArch64;ARM"\
	-DLLVM_USE_PERF=OFF\
	-DPNG_ARM_NEON=on\
	-DUSE_ALSA=OFF\
	-DUSE_AUDIOUNIT=ON\
	-DUSE_DISCORD_RPC=OFF\
	-DUSE_NATIVE_INSTRUCTIONS=OFF\
	-DUSE_PULSE=OFF\
	-DUSE_SYSTEM_FFMPEG=on\
	-DUSE_SYSTEM_MVK=on\
	-DUSE_VULKAN=ON\
	-GNinja
```

**Comment by anatoliyz** [comment]
Now `cmake` has finished successfully but `ninja` unfortunately fails...

**Comment by illusion0001** [comment]
> Hi! I'd like to build and test a native ARM build of your version for my MacBook M1 Pro. I'm following this build instructions:
> 
> https://github.com/RPCS3/rpcs3/files/10694905/RPCS3.Build.instructions.txt
> 
> I receive the following output:
> 
> ```cmake
>   Could not find a configuration file for package "LLVM" that is compatible with requested version "16.0".
> 
>   The following configuration files were considered but not accepted:
> 
>     /usr/local/opt/llvm/lib/cmake/llvm/LLVMConfig.cmake, version: 18.1.4
>     /usr/local/opt/llvm/lib/cmake/llvm/llvm-config.cmake, version: unknown
> 
> CMake Warning at 3rdparty/llvm/CMakeLists.txt:58 (find_package):
>   Could not find a configuration file for package "LLVM" that is compatible with requested version "17.0".
> 
>   The following configuration files were considered but not accepted:
> 
>     /usr/local/opt/llvm/lib/cmake/llvm/LLVMConfig.cmake, version: 18.1.4
>     /usr/local/opt/llvm/lib/cmake/llvm/llvm-config.cmake, version: unknown
> 
> CMake Error at 3rdparty/llvm/CMakeLists.txt:67 (message):
>   Can't find LLVM libraries from the CMAKE_PREFIX_PATH path or LLVM_DIR.
>   													 Enable BUILD_LLVM option to build LLVM from included as a git submodule.
>   													
> ```
> 
> Can you please provide me with support on building your version locally? Thanks in advance!

Nothing much is different from official repository. You can read the ci build scripts on how to set it up. Or read building.md
